### ISSUE TITLE
Output index for video sub-sampling

### ISSUE THREAD

**Issue by simfor** [de-Bivort-Lab/autotracker#26]
![bug181217](https://user-images.githubusercontent.com/767724/50161071-c71f7680-02a8-11e9-8c88-e073e9856893.png)

**Comment by werkhoven** [comment]
I'm looking into it, Simon. Any context you could offer about what settings you selected under the video recording menu would be helpful.

**Comment by simfor** [comment]
Great! I ticked "record video", "enable video sub-sampling", and "output video index". I think I set sub-sampling rate to -5 Hz. 

When I un-ticked "output video index", I could successfully run an experiment while outputting a sub-sampled video.

**Comment by werkhoven** [comment]
These details are very helpful, thanks. I'll try to recreate it on my end.

**Comment by werkhoven** [comment]
I was able to recreate the error, and I think the issue has been fixed. It's working on my end. Let me know how it goes.
