### ISSUE TITLE
Changing camera settings

### ISSUE THREAD

**Issue by simfor** [de-Bivort-Lab/autotracker#27]
![brightnesschange_masterbeta181220](https://user-images.githubusercontent.com/767724/50309264-2e395880-046c-11e9-8954-87391bac81f7.png)

This error occurred when trying to change the brightness in camera settings while previewing. Branch: master_beta

**Comment by werkhoven** [comment]
From the call stack, it looks like the error occurred during ROI detection, not during previewing. It looks like the camera session was somehow closed. Again, any specific details you can provide on the sequence of events would be helpful.

**Comment by simfor** [comment]
It might have been during ROI detection. But the error seemed to be triggered by the change in camera settings in the GUI

**Comment by werkhoven** [comment]
Alright, I'll look into it. It was not intentional to allow editing camera settings during ROI detection. For now at least, just tweak camera settings during the camera preview.
