### ISSUE TITLE
Camera disconnected

### ISSUE THREAD

**Issue by npittoors** [de-Bivort-Lab/autotracker#35]
Margo stopped experiment with 3:03:01 left in a 24h long experiment (computer 3). The camera was connected...I restarted margo and played with the camera settings, we'll see if it errors out again. 

![NicoleErrora042619](https://user-images.githubusercontent.com/45102970/55037173-3ec11800-4ff3-11e9-9d95-f876b5e66224.JPG)
![NicoleErrorb042619](https://user-images.githubusercontent.com/45102970/55037172-3ec11800-4ff3-11e9-82b7-9bb2bef61b18.JPG)

**Comment by werkhoven** [comment]
This is a hardware issue. MARGO should throw up an error if the camera suddenly disconnects.
