### ISSUE TITLE
The tracking target is lost when it moves rapidly

### ISSUE THREAD

**Issue by chen1356291** [de-Bivort-Lab/autotracker#43]
Our laboratory used Margo to track zebrafish larvae, but zebrafish moved too fast, resulting in the target being often lost.So what is the solution? Thank you!

**Comment by debivort** [comment]
Are you worried about the image of the fish being lost from frame to frame? If so, I believe the only solution would be to increase your frame rate on the camera and computer end. If the worry is not frames where the fish cannot be seen, but instead missing track points in these frames - perhaps you could interpolate missing track values? 

Are you doing multi-animal or single animal experiments?

**Comment by chen1356291** [comment]
> Are you worried about the image of the fish being lost from frame to frame? If so, I believe the only solution would be to increase your frame rate on the camera and computer end. If the worry is not frames where the fish cannot be seen, but instead missing track points in these frames - perhaps you could interpolate missing track values?
> 
> Are you doing multi-animal or single animal experiments?

Our experiment is to study epilepsy, using 5dpf zebrafish larvae to make a model. 12 well cell plates were used, and one zebrafish was placed in each well. After modeling with modeling agent, record the video and use Margo for offline tracking. The larvae will move quickly under the action of modeling agent, the centroid circle positioned on the larvae will disappear, the trajectory will be lost, and the output data may be inaccurate. These are all things I worry about.

**Comment by chen1356291** [comment]
> Are you worried about the image of the fish being lost from frame to frame? If so, I believe the only solution would be to increase your frame rate on the camera and computer end. If the worry is not frames where the fish cannot be seen, but instead missing track points in these frames - perhaps you could interpolate missing track values?
> 
> Are you doing multi-animal or single animal experiments?

Our experiment is to study epilepsy, using 5dpf zebrafish larvae to make a model. 12 well cell plates were used, and one zebrafish was placed in each well. After drug treatment, Margo is used for offline tracking. The larvae will move quickly under the action of drugs, the centroid circle positioned on the larvae will disappear, the trajectory will be lost, and the output data may be inaccurate. These are my worries.

**Comment by chen1356291** [comment]
> interpolat

Our experiment is to study epilepsy, using 5dpf zebrafish larvae to make a model. 12 well cell plates were used, and one zebrafish was placed in each well. After drug treatment, Margo is used for offline tracking. The larvae will move quickly under the action of drugs, the centroid circle positioned on the larvae will disappear, the trajectory will be lost, and the output data may be inaccurate. These are my worries. In addition, the computer performance problem you mentioned may also be the cause of this problem. Another thing you mentioned is how to insert the missing track value.Because I know nothing about computer programming, I just use Margo software to complete my experiment, these problems make me very distressed.

**Comment by chen1356291** [comment]
> Are you worried about the image of the fish being lost from frame to frame? If so, I believe the only solution would be to increase your frame rate on the camera and computer end. If the worry is not frames where the fish cannot be seen, but instead missing track points in these frames - perhaps you could interpolate missing track values?
> 
> Are you doing multi-animal or single animal experiments?

I did a multi animal tracking experiment, using 12 well cell plates to physically isolate 12 zebrafish larvae. After drug treatment, zebrafish larvae move significantly faster than the blank group. Using Margo to track the blank group can be tracked. After tracking the drug treatment group, if zebrafish larvae move faster, the centroid circle will disappear, and then zebrafish larvae move slower, the centroid circle will reappear. I'm distressed by the problems

**Comment by chen1356291** [comment]
> > Are you worried about the image of the fish being lost from frame to frame? If so, I believe the only solution would be to increase your frame rate on the camera and computer end. If the worry is not frames where the fish cannot be seen, but instead missing track points in these frames - perhaps you could interpolate missing track values?
> > Are you doing multi-animal or single animal experiments?
> 
> I did a multi animal tracking experiment, using 12 well cell plates to physically isolate 12 zebrafish larvae. After drug treatment, zebrafish larvae move significantly faster than the blank group. Using Margo to track the blank group can be tracked. After tracking the drug treatment group, if zebrafish larvae move faster, the centroid circle will disappear, and then zebrafish larvae move slower, the centroid circle will reappear. I'm distressed by the problems

**Comment by chen1356291** [comment]
> 您是否担心鱼的图像会逐帧丢失？如果是这样，我相信唯一的解决方案是提高相机和计算机端的帧速率。如果担心的不是看不到鱼的帧，而是这些帧中缺少轨迹点 - 也许您可以插入丢失的轨迹值？
> 
> 你是在做多动物实验还是单一动物实验？

In this case, the track points in the frame I told you are more consistent. If this is the reason, how to insert the missing track value? Please forgive me for my ignorance of computer knowledge

**Comment by chen1356291** [comment]
> 如果是这样，我相信唯一的解决方案是提高摄像头和帧的帧速度。如果担心的计算机不是看不到鱼的帧的帧，则可以在帧中执行任务。可能会留下你的名字预测值？
> 
> 你是在做多动物实验还是单一动物实验？

My problem should be the lack of track points in the frame. If this is the reason, how should I insert the missing track values? Please forgive my ignorance of computer knowledge

**Comment by chen1356291** [comment]
> Are you worried about the image of the fish being lost from frame to frame? If so, I believe the only solution would be to increase your frame rate on the camera and computer end. If the worry is not frames where the fish cannot be seen, but instead missing track points in these frames - perhaps you could interpolate missing track values?
> 
> Are you doing multi-animal or single animal experiments?

I used a 12 well cell plate for multi animal tracking, with one zebrafish larva per well. Margo can track the larvae of the blank group, but if the zebrafish larvae treated with modeling drugs move too fast, the centroid circle will disappear until the zebrafish larvae slow down, but in this process, the zebrafish image can be seen, so I'm worried about the inaccurate data output in the tracking process, which is a worrying problem.

**Comment by debivort** [comment]
My sense is this would best be addressed on the hardware side. You probably need to increase the sharpness of the fast-moving fish in each frame. A faster camera may be needed, but it's also possible you can increase the amount of illumination and reduce the shutter/exposure time. This will produce a crisper image that may track better. Hopefully the treated fish aren't that much faster, so you can achieve better tracking with modest changes to the camera settings and illumination.

**Comment by chen1356291** [comment]
> My sense is this would best be addressed on the hardware side. You probably need to increase the sharpness of the fast-moving fish in each frame. A faster camera may be needed, but it's also possible you can increase the amount of illumination and reduce the shutter/exposure time. This will produce a crisper image that may track better. Hopefully the treated fish aren't that much faster, so you can achieve better tracking with modest changes to the camera settings and illumination.

Thank you for your suggestion. I'll try what you said. Thank you again

**Comment by chen1356291** [comment]
There's another question to ask you. Why do you track zebrafish larvae with green dots in your sample video, while I track zebrafish larvae with red circles @debivort

**Comment by debivort** [comment]
Ha, I'm not sure. I suspect it just reflects an earlier version of the code.

**Comment by chen1356291** [comment]
> Ha, I'm not sure. I suspect it just reflects an earlier version of the code.

Well, thank you very much.

**Comment by chen1356291** [comment]
At present, my collection device is to place the cell plate with zebrafish larvae flat on a 22 watt LED light board, and the camera collects them above. I bought a 50 Watt light that hasn't arrived yet, so I first adjusted the camera parameters, adjusted the shutter to 1 / 12800, and imported the collected video into Margo for offline tracking, but I still can't track the larvae that move faster. Originally, the moving track of zebrafish was a smooth curve, However, due to the fast moving speed, the moving track becomes a straight line, so a lot of data is lost, so  I'm very flustered now. Maybe my experiment will suddenly stop. Help @debivort

**Comment by debivort** [comment]
Post a screenshot of what the problematic tracking looks like.

**Comment by chen1356291** [comment]
![9JH ` 2RP9~1KV`4WXD7THN](https://user-images.githubusercontent.com/104889465/167137275-aeb54d56-3d18-4da1-8caa-f2e276ace93c.png)
There are two situations that cannot be tracked. The first is that the tracking circle disappears, similar to the first hole. The other is that the zebrafish larvae have swam to the next position and the tracking circle is still in place, similar to the eighth hole @debivort

**Comment by debivort** [comment]
It may be that the minimum and maximum blob size parameters need adjusting. If the fish blob appears too small (below that tunable parameter), it will not track. Have you tried adjusting that?

**Comment by chen1356291** [comment]
> It may be that the minimum and maximum blob size parameters need adjusting. If the fish blob appears too small (below that tunable parameter), it will not track. Have you tried adjusting that?

I haven't adjusted it. A video with high resolution was recorded before, After importing Margo, the display ratio is 0.068/1.3. Later, the video with low resolution was collected, After importing Margo, the display ratio was 0.15/2.8

**Comment by debivort** [comment]
Try adjusting those parameters. They are well documented in the wiki.

**Comment by chen1356291** [comment]
> 尝试调整这些参数。它们在 wiki 中有详细记录。

okay, thank you

**Comment by chen1356291** [comment]
Thank you very much for your guidance and solving one of my big problems. It took me so long because I didn't know about image processing. Thank you again. I'm a Chinese. If you have the opportunity to come to China, I hope to have dinner with you and express my gratitude to you. @debivort

**Comment by debivort** [comment]
Very glad to hear the tracking is working better. That's a very kind invitation. I have been to China a couple times previously and always enjoyed the exchange. Maybe it could happen one day!

**Comment by werkhoven** [comment]
Marking as resolved.
