### ISSUE TITLE
isnan issue when labelling subsets of ROIs

### ISSUE THREAD

**Issue by dlavrent** [de-Bivort-Lab/autotracker#45]
de Bivort lab projector rig 1, MATLAB R2023a, latest version of margo

We set up a ymaze experiment and input the following labels:
| Strain | Sex | Treatment | ROI start | ROI End | ID Start | ID End | Day # | Box # | Tray # | Comments|
| - | - | - | - | - | - | - | - | - | - | - | 
| s1 | f | t1 | 11 | 40 | 1 | 30 | 1 | 1 | 10 | |
| s1 | m | t1 | 47 | 51 |  31 | 35 | 1 | 1 | 10 | |

This resulted in the following "Error encountered - tracking stopped" popup:
```
Undefined function 'isnan' for input arguments of type 'cell'.
Error in autoInitialize (line 119)
    if ~isnan(expmt.meta.labels_table{1,i})

Error in run_ymaze (line 36)
[trackDat,expmt] = autoInitialize(trackDat,expmt,gui_handles);

Error in margo>run_pushbutton_Callback (line 770)
    expmt = feval(handlesexperiments(exp_idx).run, expmt, handles);

Error in gui_mainfcn (line 95)
    feval(varargin{:});

Error in margo (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)margo('run_pushbutton_Callback',hObject,eventdata,guidata(hObject))
```

The error in the MATLAB command window:
```
Incorrect number or types of inputs or outputs for function 'isnan'.

Error in autoInitialize (line 119)
            if ~isnan(expmt.meta.labels_table{1,i})

Error in run_ymaze (line 36)
[trackDat,expmt] = autoInitialize(trackDat,expmt,gui_handles);

Error in margo>run_pushbutton_Callback (line 770)
    expmt = feval(handles.experiments(exp_idx).run, expmt, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in margo (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)margo('run_pushbutton_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.
```

When putting in the following ROI sets in the labels, there was no issue starting up tracking:
| Strain | Sex | Treatment | ROI start | ROI End | ID Start | ID End | Day # | Box # | Tray # | Comments|
| - | - | - | - | - | - | - | - | - | - | - | 
| s1 | f | t1 | 11 | 40 | 1 | 30 | 1 | 1 | 10 | |
| s1 | m | t1 | 1 | 10 |  31 | 40 | 1 | 1 | 10 | |

**Comment by werkhoven** [comment]
Issue fixed by: https://github.com/de-Bivort-Lab/margo/tree/hotfix/zwerkho-fixed-label-maker-roi-range-issue
