### ISSUE TITLE
ROI remove error (Proj Rig 2)

### ISSUE THREAD

**Issue by sdot61** [de-Bivort-Lab/autotracker#53]
When manually removing ROI's, margo can stop working entirely. Attaching log below for Proj. Rig 2. This error can happen on any Margo (has been noted occuring on other of our PC's) albeit, infrequently.
[ROIremov_err_Proj_Rig2_02_09_24.txt](https://github.com/de-Bivort-Lab/margo/files/14226221/ROIremov_err_Proj_Rig2_02_09_24.txt)

**Comment by werkhoven** [comment]
Closing the issue because it's duplicated by: https://github.com/de-Bivort-Lab/margo/issues/48
