### ISSUE TITLE
Referencing bugs

### ISSUE THREAD

**Issue by simfor** [de-Bivort-Lab/autotracker#6]
Bugs/errors occurring during referencing

![referencingbug](https://user-images.githubusercontent.com/767724/47673051-e859c580-db89-11e8-8b80-6df619278ad3.png)

![screenshot from 2018-10-29 14-45-20](https://user-images.githubusercontent.com/767724/47673059-edb71000-db89-11e8-9f63-139042dd983b.png)

**Comment by werkhoven** [comment]
This issue should be fixed in more recent commits of `master_beta`. No function named: `matchCentroids2ROI` exists in recent versions of autotracker/margo. Some of your problems may be coming from conflicting functions on MATLAB's search path. AFAIK, `matchCentroids2ROIs` was removed quite a while back. So it looks like either you have version conflicts or you are using an older branch.

Is this coming from the `carolyn` branch?

**Comment by simfor** [comment]
Yes this is from the Carolyn branch. I was hoping it would be more stable than master_beta

**Comment by werkhoven** [comment]
I'm a bit confused, because the error messages show two different call stacks. One looks like a newer call stack and one looks like an older call stack. Are these errors from two different branches?

**Comment by simfor** [comment]
That might be the case. Sorry about the confusion. I've been saving screenshots from various errors and thought I'd put them here. The matchCentroids2ROI error is definitely from the carolyn branch but the other one might be from master_beta

**Comment by werkhoven** [comment]
After talking to our post-doc about the branch she's using, it appears to be a variant of the `file_recover` branch. I'm going to push a version called `master_alpha` for posterity sake.

The other errors you posted from the `master_beta` branch were resolved in a previous commit. Unless those errors are from the most recent commit, I'm going to mark them resolved.

**Comment by werkhoven** [comment]
I pushed a version of the branch that she is using to a new remote branch `master_alpha`. I cannot make any guarantees about this commit or whether or not it will make your life any easier. It does have issues on the play button with running multiple experiments back to back which, according to her, can usually be overcome by hitting the play button twice. You may notice that a lot of features are missing, such as the lack of ellipsoid shaped ROIs (even though the dropdown menu says you can create them).
